### ISSUE TITLE
Reddit Companion shows Companion bar on reddit.com for link posts that have "reddit.com" as URL

### ISSUE THREAD

**Issue by withmorten** [creesch/reddit-companion#2]
Example:

https://www.reddit.com/r/redditrequest/comments/3jdwi4/requesting_rtexassucks_mod_is_inactive/

![image](https://cloud.githubusercontent.com/assets/765123/9706818/7673a97e-54f3-11e5-8158-7e8ebc7af64c.png)

I have not visited that post, and the companion bar showed up out of the blue on the front-page.

Not sure how to replicate it, but it did happen.

My solution would be to ignore all reddit.com submissions when not coming from that submission, if that's at all possible.

**Comment by creesch** [comment]
I can't replicate that unless I actually come from that post. I'll keep an eye out for it.

**Comment by withmorten** [comment]
Yeah, I couldn't really replicate it either. It was odd though. Just popped up on the front page for some reason.
