### ISSUE TITLE
Covers up "top-of-page" banners

### ISSUE THREAD

**Issue by wickles** [creesch/reddit-companion#3]
Lots of pages these days have banners that sit at the top of the screen even when you scroll. Companion pushes the rest of the page down but not the banner and ends up sitting on top of it, covering it up. Any way to fix this? 

![screen shot 2015-09-10 at 8 52 16 am](https://cloud.githubusercontent.com/assets/4229542/9793264/76ac1748-5799-11e5-8830-ee98d6f61a55.png)

**Comment by creesch** [comment]
Hrm... I think so I'll have to test it properly though since it might mess up other pages again.

edit: 

Just tested it, I can fix it for some websites but for youtube (as shown in your example) I can't really fix it due to how the page is build up.

**Comment by jmorais** [comment]
Did a fix for this issue. Instead of margin-top, I made a tranform in the entire html tag, pushing it down 30px  `-webkit-transform: translate(0,30px)` and pushing up the shinebar 30px `-webkit-transform: translate(0,-30px)`. Guess it solves the problem, but I'm not sure if it has any side effects.
